Feature/#121
sulton-max/Training.AirBnb.Clone pull request #134
Opened 2023-10-13 10:45 UTC by FirdavsAsadov

2023-10-13 12:25 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/Description.cs
> +
Ishlatilmayotgan directive lar (namspace) o'chirib tashlanishi kerak.

2023-10-13 12:40 UTC, Ilxom-22 requested changes

2023-10-13 12:40 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/ListingDescriptionService.cs
> +    public ListingDescriptionService(IDataContext dataContext)
Property va constructor va barcha methodlar o'rtasida bittadan bo'sh qator bo'lishi shart.

2023-10-13 12:40 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/ListingDescriptionService.cs
> +            .IsNullOrWhiteSpace(description.ListingDescription))
IsNullOrWhiteSpace ishlatilganda IsNullOrEmpty ishlatilishi shart emas.

2023-10-14 04:00 UTC, Abdurahmon0412 requested changes

2023-10-14 04:00 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/Description.cs
> +public class Description : SoftDeletedEntity
4 va 5 qator o'rtasida bo'sh qator bo'lgani yaxshiroq

2023-10-17 08:04 UTC, Abdurahmon0412 submitted a review, later dismissed

2023-10-17 08:08 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/DescriptionService.cs
> +        return foundlistingdescription;
logikani qatorlar bilan ajratib chiqish kerak

2023-10-17 08:08 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/DescriptionService.cs
> +        return removedListingDescription;
logikani qatorlar bilan ajratib chiqish kerak

2023-10-17 14:05 UTC, Abdurahmon0412 submitted a review, later dismissed

2023-10-17 14:30 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/DescriptionService.cs
> +
Incorrect Validation

2023-10-19 10:31 UTC, Abdurahmon0412 approved these changes

2023-10-19 10:48 UTC, Habiba67y commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/DescriptionService.cs
> +        if (string.IsNullOrWhiteSpace(description.TheSpace))
manimcha bunaqa qilish ortiqcha bo'sa kerak, the space propertysi nullable ekan shundoq ham

2023-10-19 12:54 UTC, Ilxom-22 approved these changes

2023-10-19 12:54 UTC, merged