Implement loaction foundation service
sulton-max/Training.AirBnb.Clone pull request #135
Opened 2023-10-14 16:18 UTC by Habiba67y

2023-10-14 23:41 UTC, Ilxom-22 requested changes

2023-10-14 23:41 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/Location.cs
> +}
AddressId property dan tashqari hamma property lar nullable bo'lishi kerak, chunki faqatgina addressId required qolganlari optional hisoblanadi, Host hohlasa kiritadi hohlamasa yo'q.

2023-10-14 23:41 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/LocationServices/IEntityBaseService.cs
> +}
Bu bo'sh interface ni nega yaratdingiz?

2023-10-14 23:41 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/LocationServices/LocationService.cs
> +
Ishlatilmayotgan directive larni (namespace) o'chirib tashlash kerak. (System.Reflection.Metadata ishlatilmagan).

2023-10-14 23:41 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/LocationServices/LocationService.cs
> +    public LocationService(IDataContext dataContext)
Readability uchun property lar va constructor orasida bitta bo'sh qator bo'lgani maqul.

2023-10-14 23:41 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/LocationServices/LocationService.cs
> +        await _appDataContext.Locations.AddAsync(location, cancellationToken);
Location entity Create bo'lganda unique ekanligiga validatsiya qilish kerak. Yani birxil addressId lik 2 va undan ko'p location bo'lishi mumkin emas, chunki har bir listing uchun aloxida address entity yaratiladi hattoki ularning addressi birxil bo'lsa ham. 

Undan tashqari optional bo'lgan NeighborhoodDescription va GettingAround propertylari whitespace bo'lib qolishi mumkin, bu holda ularni null ga tenglab qo'yish kerak,  chunki front end bu propertylarni null bo'lsa ekranga chiqarib o'tirmaydi, agar null bo'lmasa lekin bo'sh string bo'lsa ham front end buni tekshirib o'tirmasdan ekranga chiqarib yuboradi va bu noto'g'ri bo'ladi.

2023-10-14 23:41 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/LocationServices/LocationService.cs
> +        => _appDataContext.Locations.Where(predicate.Compile()).AsQueryable();
_appDataContext.Locations ichidan query qilinganda u IsDeleted property si true bo'lganlarni ham query qilib olib keladi, yani allaqachon o'chirib yuborilgan locationlarni. O'chib ketgan location lar hech qaysi service tomonidan foydalanilmaydi, va u user larga ham ko'rsatilmaydi, shuning uchun alohida Locationlar ichidan faqat active larini query qilib qaytaradigan private method yozib qo'ygan maqul, va shu query ustiga query joining qilib Get methodi ishlatiladi (appDataContext o'rniga). Boshqa crud service larni ko'rib chiqsangiz deyarli hammasida shunday ishlatilgan.

2023-10-14 23:41 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/LocationServices/LocationService.cs
> +        foundLocation.AddressId = location.AddressId;
AddressId hechqachon update bo'lmaydi, chunki u alohida table da saqlanadi. Address o'zgarsa address entity o'zi update bo'ladi, lekin uni id si o'zgarmaydi.

2023-10-15 08:59 UTC, Habiba67y commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/Location.cs
> +}
aha tushunarli

2023-10-15 09:00 UTC, Habiba67y commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/LocationServices/LocationService.cs
> +
ok

2023-10-15 09:02 UTC, Habiba67y commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/LocationServices/LocationService.cs
> +        await _appDataContext.Locations.AddAsync(location, cancellationToken);
tushunarli

2023-10-15 09:03 UTC, Habiba67y commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/LocationServices/LocationService.cs
> +        foundLocation.AddressId = location.AddressId;
ok

2023-10-15 09:04 UTC, Abdurahmon0412 submitted a review, later dismissed

2023-10-15 09:51 UTC, Ilxom-22 approved these changes

2023-10-15 10:26 UTC, Abdurahmon0412 approved these changes

2023-10-15 10:26 UTC, merged