Listing rules service created
sulton-max/Training.AirBnb.Clone pull request #147
Opened 2023-10-18 12:43 UTC by abdura52

ListingRules service created

2023-10-18 13:03 UTC, Ilxom-22 requested changes

2023-10-18 13:03 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/ListingRules.cs
> +
CheckOutTime nullable bo'mi qobti.

2023-10-18 13:04 UTC, abdura52 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/ListingRulesService.cs
> +        {
bitta character nimalarga olib kemidi 🤣

2023-10-18 13:05 UTC, abdura52 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/ListingRules.cs
> +
CheckOutTime nullable bo'lmagan saytda ham

2023-10-18 13:21 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/ListingRules.cs
> +
Ha CheckInEndTime bilan adashtirvorimman.

2023-10-18 13:39 UTC, Abdurahmon0412 requested changes

2023-10-18 13:39 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/ListingRulesService.cs
> +    {
entityni listingrulesga o'zgartirsayiz bo'ladi

2023-10-18 13:39 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/ListingRulesService.cs
> +    {
Delete methodi eng oxirida updatedan keyin bo'adi

2023-10-18 13:39 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/ListingRulesService.cs
> +
returindan keyin qator tashlamasayizham bo'ladi redibility uchun

2023-10-18 13:39 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/ListingRulesService.cs
> +            ?? throw new EntityNotFoundException<ListingRules>("Entity not found with this id");
hamma joyda _contextni o'rniga bitta undeleted methodni yozib o'shaniishlatsayiz bo'ladi

2023-10-18 13:39 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/ListingRulesService.cs
> +    {
bu yerdaham entitylarni almashtirib yuborasiz

2023-10-18 13:39 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/ListingRulesService.cs
> +
ifda o'zi hamma narsa bir qatorda ekanku scop nega kerak 
bu xato emas prosta redibility uchun

2023-10-18 16:26 UTC, Habiba67y approved these changes

2023-10-18 21:05 UTC, Ilxom-22 approved these changes

2023-10-19 04:28 UTC, Abdurahmon0412 approved these changes

2023-10-19 04:28 UTC, merged