created seed data for addreses and locations
sulton-max/Training.AirBnb.Clone pull request #148
Opened 2023-10-18 13:36 UTC by Habiba67y

2023-10-18 13:44 UTC, Abdurahmon0412 approved these changes

2023-10-18 13:44 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Persistence/SeedData/LocationSeedData.cs
> +    {
methodni ichida listni qabul qilgansiz o'shani o'rniga contextni ichidaham borku citylar o'shandan foydalansayizam 
bo'lardi bu xato emas lekin

2023-10-18 13:52 UTC, Ilxom-22 requested changes

2023-10-18 13:52 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Persistence/SeedData/LocationSeedData.cs
> +        {
Har bir city uchun bittadan address yaratilgan. Lekin address listing ga qarab generate bo'ladi, yani har bitta listingga bittadan address bo'ladi. Agar 1000 ta listing bo'lsa 1000 ta address bo'lishi kerak degani. Shunga method ichiga count degan parameter qabul qilib olib nechta so'ralgan bo'lsa shuncha generate qilib bergan maqul, chunki bu fake data, va listing ga aloqador. City larni foreachda aylanib o'tirmasdan citylar ichidan random tanlansa bo'ladi.

2023-10-18 13:54 UTC, Habiba67y commented on src/Training.AirBnb.Clone.Backend/Backend Project/Persistence/SeedData/LocationSeedData.cs
> +    {
ok

2023-10-18 13:56 UTC, Habiba67y commented on src/Training.AirBnb.Clone.Backend/Backend Project/Persistence/SeedData/LocationSeedData.cs
> +        {
aha tushunarli

2023-10-18 15:18 UTC, Abdurahmon0412 approved these changes

2023-10-19 12:30 UTC, Ilxom-22 submitted a review, later dismissed

2023-10-19 12:53 UTC, Abdurahmon0412 submitted a review, later dismissed

2023-10-19 12:55 UTC, Ilxom-22 approved these changes

2023-10-19 12:55 UTC, Abdurahmon0412 approved these changes

2023-10-19 12:55 UTC, merged