Feature/#142
sulton-max/Training.AirBnb.Clone pull request #154
Opened 2023-10-20 11:07 UTC by FirdavsAsadov

2023-10-20 12:43 UTC, Ilxom-22 requested changes

2023-10-20 12:43 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/BlockedNightService.cs
> +            return false;
Huddi shu listingda huddi shu kunida boshqa block bor yo'qligiga validatsiya qo'shilmagan. Chunki bir kunga 2 ta block qo'yib bo'lmaydi.

2023-10-20 12:43 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/BlockedNightService.cs
> +            throw new EntityValidationException<BlockedNight>("this days are gone");
Exception ichida manoliroq message berish kerak

2023-10-20 14:13 UTC, Ilxom-22 requested changes

2023-10-20 14:13 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/BlockedNightService.cs
> +            return false;
Shoshilib yozgansiz logikasi notog'ri. BlockedNights any ichida date va listingId lari birxili chiqib qolsa false qaytarish kerak. Listing object ichidan qidirish kerak emas, blockedNights ichida listingId property bor.

2023-11-04 04:46 UTC, Abdurahmon0412 approved these changes

2023-11-04 04:49 UTC, Ilxom-22 approved these changes

2023-11-04 04:50 UTC, Abdurahmon0412 approved these changes

2023-11-04 04:50 UTC, merged