add AuthService
sulton-max/Training.AirBnb.Clone pull request #187
Opened 2023-11-09 07:22 UTC by FirdavsAsadov

2023-11-09 09:59 UTC, Ilxom-22 requested changes

2023-11-09 09:59 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Application/Identity/Service/IAuthService.cs
> +        ValueTask<bool> RegisterAsync(RegistrationDetails registrationDetails, string password);
password parameter is redundant

2023-11-09 09:59 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/AccountServices/AccessTokenGeneratorService.cs
> +                new (ClaimConstant.UserId, user.Id.ToString())
Add user role in the claims

2023-11-09 09:59 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/AccountServices/AuthService.cs
> +        {
password parameter is redundant

2023-11-09 09:59 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/AccountServices/AuthService.cs
> +        private readonly IDataContext _dataContext;
IDataContext AuthService ichiga inject qilinmidi

2023-11-09 09:59 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/AccountServices/AuthService.cs
> +            var exsistingUser = _dataContext.Users.FirstOrDefault(user => user.EmailAddress == loginDetails.EmailAddress);
AccountService dan foydalanib userlarni query qilish kerak.

2023-11-09 13:30 UTC, Abdurahmon0412 requested changes

2023-11-09 13:30 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/AccountServices/AuthService.cs
> +
EntityNotFoundException generic qilib yuborin

2023-11-09 13:30 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/AccountServices/AccountService.cs
> +    public User GetUserByEmailAddress(string emailAddress)
Sherdaham qator tashlab keting

2023-11-09 13:30 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/AccountServices/AuthService.cs
> +                FirstName = registrationDetails.FirstName,
Id ni bazani o'zi yozib beradi

2023-11-09 13:30 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/AccountServices/AccountService.cs
>              Password = _passwordHasher.Hash(password)
37 chi Qatorni o'chirib tashlan

2023-11-13 05:31 UTC, Ilxom-22 approved these changes

2023-11-13 11:37 UTC, Abdurahmon0412 approved these changes

2023-11-13 11:37 UTC, merged