#feature/182LocationManagementService
sulton-max/Training.AirBnb.Clone pull request #189
Opened 2023-11-09 11:05 UTC by Abdurahmon0412

2023-11-09 13:54 UTC, Ilxom-22 requested changes

2023-11-09 13:54 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/CompositionServices/LocationManagementService.cs
> +        var addresses = _addressService
Address bilan location one to one relationship. Shuning uchun list qilib address lar qaytmidi. Bittagina address qaytadi shuni o'chirib yuborish kerak.

2023-11-09 13:54 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/CompositionServices/LocationManagementService.cs
> +            throw new EntityNotUpdatableException<ScenicView>("this scenic view not updatable");
locationScenicViews cannot be null. Check for empty collection.

2023-11-09 13:54 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/CompositionServices/LocationManagementService.cs
> +            throw new EntityNotDeletableException<ScenicView>("this scenicview not deletable");
Huddi shu joyi tepadagi method da ham qaytarilgan. DRY principiga ko'ra (DON'T REPEAT YOURSELF) bir xil code ikki marta qaytarilsa uni aloxida methodga olib qo'yish kerak.

2023-11-13 05:33 UTC, Ilxom-22 approved these changes

2023-11-13 11:37 UTC, Xolmuratov02 approved these changes

2023-11-13 11:37 UTC, merged