Initialize Project
sulton-max/Training.AirBnb.Clone pull request #215
Opened 2023-11-17 08:06 UTC by Xolmuratov02

2023-11-17 09:06 UTC, boburjon1504 approved these changes

2023-11-17 09:07 UTC, boburjon1504 commented
Mainga bo'lib qoptiku

2023-11-17 09:11 UTC, Xolmuratov02 commented
Yoq qanday qilib ketib qolibdi hayronman

2023-11-17 09:30 UTC, Ilxom-22 requested changes
main ga PR tashab qo'yibsiz.

2023-11-17 09:34 UTC, Xolmuratov02 commented
Ha endi o'zgartirib qoyaman

пт, 17 нояб. 2023 г., 14:30 Ilxom Karimjonov ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> main ga PR tashab qo'yibsiz.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sulton-max/Training.AirBnb.Clone/pull/215#pullrequestreview-1736463285>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A46ARGTODSRKVYFYXHYFZF3YE4VDXAVCNFSM6AAAAAA7PMSI56VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMZWGQ3DGMRYGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-17 09:52 UTC, Ilxom-22 requested changes

2023-11-17 09:52 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/AirBnB.Api.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
Entity Framework o'rnatish sizga berilgan issue da yo'q.

2023-11-17 09:52 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Configurations/HostConfiguration.cs
> +            //.AddPersistence()
AddPersistence qolib ketibti.

2023-11-17 16:03 UTC, Ilxom-22 approved these changes

2023-11-18 03:51 UTC, Ilxom-22 approved these changes

2023-11-18 03:58 UTC, boburjon1504 approved these changes

2023-11-18 03:58 UTC, merged