Base Entities
sulton-max/Training.AirBnb.Clone pull request #218
Opened 2023-11-18 16:51 UTC by Amonov996

Add Base Entities,
Add NotificationDbContext
Add EntitiyRepositoryBase
Install NuGet EFCore on Persistence

2023-11-19 02:16 UTC, boburjon1504 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Repositories/EntityRepositoryBase.cs
> +    protected EntityRepositoryBase(DbContext dbContext)
Shu yerida construktorni o'zidan TContextni bersez ortiqcha castga hojat qolmendi

2023-11-19 05:48 UTC, Amonov996 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Repositories/EntityRepositoryBase.cs
> +    protected EntityRepositoryBase(DbContext dbContext)
Qanday qilib ? Misol keltira olasizmi ?

2023-11-19 17:10 UTC, Ilxom-22 requested changes

2023-11-20 09:46 UTC, Abdurahmon0412 requested changes

2023-11-20 09:46 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/CreationAuditableEntity.cs
> +}
qo'shimcha 3 ta ochilgan iterfacelarga class bo'lishi shart emas shunchaki interfaceni o'zi bo'lsa yetarli yani CreationAuditableEntity shart emas interfaceni o'zi yetarli

2023-11-20 09:46 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/ICreationAuditableEntity.cs
> +}
buni bitta 
Guid CreatedBy property si bo'lishi kerak

2023-11-20 09:46 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/IDeletionAuditableEntity.cs
> +}
Bu AuditableEntitydan olishi shart emas
va bunda ham bittta DeletedBy propertysi bo'lishi kerak Guid tipida

2023-11-20 09:46 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/IModificationAuditableEntity.cs
> +}
Bunda ham bitta ModifiedBy property bo'ladi Guid tipida

2023-11-20 09:46 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/ISoftDeletedEntity.cs
> +{
ISoftDeleted faqatgina IAuditabledan olsa yeta

2023-11-20 09:46 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/SoftDeletedEntity.cs
> +    public Guid Id { get; set; }
SoftDeletedEntity : AuditableEntity, ISoftDeletedEntity
softdeletedni o'zi mana shunay oladi

2023-11-20 09:46 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Repositories/EntityRepositoryBase.cs
> +    protected EntityRepositoryBase(DbContext dbContext)
pretocted constructorda DbContext dbContext deb emas balki TContext dbContext deb qabul qilasiz va keyin tepadagi strelkadan keyingi qavsni o'chirib tashlasayiz ham bo'ladi

2023-11-20 11:33 UTC, Ilxom-22 requested changes

2023-11-20 11:33 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/Entity.cs
> +public class Entity : IEntity
Common classlar abstract class bo'lishi kerak.

2023-11-21 08:29 UTC, Abdurahmon0412 approved these changes

2023-11-22 02:23 UTC, sulton-max requested changes

2023-11-22 02:23 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/ICreationAuditableEntity.cs
> +    public Guid CreatedBy { get; set; }
Update to `CreatedByUserId` and add docs

2023-11-22 02:23 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/IDeletionAuditableEntity.cs
> +    public Guid DeletedBy { get; set; }
Update to `DeletedByUserId` and add docs

2023-11-22 02:23 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/IAuditableEntity.cs
> +public interface IAuditableEntity : ISoftDeletedEntity
Add docs

2023-11-22 02:23 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/Entity.cs
> +public abstract class Entity : IEntity
Add docs

2023-11-22 02:23 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/AuditableEntity.cs
> +public abstract class AuditableEntity : SoftDeletedEntity, IAuditableEntity
Add docs

2023-11-22 02:23 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/IEntity.cs
> +public interface IEntity
Add docs

2023-11-22 02:23 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/ISoftDeletedEntity.cs
> +public interface ISoftDeletedEntity : IEntity
Add docs

2023-11-22 02:23 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Common/IModificationAuditableEntity.cs
> +    public Guid ModifiedBy { get; set; }
Update to `ModifiedByUserId` and add docs

2023-11-22 02:23 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/DataContexts/NotificationDbContext.cs
> +    public NotificationDbContext(DbContextOptions<NotificationDbContext> options) : base(options)
Use primary constructor, update projects to .net 8

2023-11-22 02:23 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Repositories/EntityRepositoryBase.cs
> +public abstract class EntityRepositoryBase<TEntity, TContext> where TEntity : class, IEntity where TContext : DbContext
Add docs

2023-11-22 12:55 UTC, Xolmuratov02 approved these changes

2023-11-23 09:36 UTC, sulton-max approved these changes
Good job

2023-11-23 10:05 UTC, merged