Feature/#198
sulton-max/Training.AirBnb.Clone pull request #221
Opened 2023-11-27 05:44 UTC by Abdurahmon0412

2023-11-27 10:22 UTC, botirjonabdumannonovv approved these changes

2023-11-28 06:42 UTC, botirjonabdumannonovv submitted a review, later dismissed

2023-11-28 08:15 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/global.json
> +{
qayerlarida qolib ketganini hammasini yozib ketsayiz yaxshi bo'lardi ancha joyiga qo'shdim docs ni

2023-11-29 07:46 UTC, sulton-max requested changes

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/Notifications/Services/ISmsTemplateService.cs
> +    /// it takes smsTemplate by filtering
Change comment to "Retrieves SMS templates by filter"

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/Notifications/Services/ISmsTemplateService.cs
> +    /// it takes smsTemplate By type
Change comment to "Retrieves SMS template by type"

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/Notifications/Services/ISmsTemplateService.cs
> +    /// it creates by emailTemplate
Change comment to "Creates SMS template"

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/Notifications/Services/IEmailTemplateService.cs
> +    /// it takes emailTemplate by filtering
Change just like in the comments of SMS template service

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/AirBnB.Infrastructure.csproj
> +    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.8.1" />
Why we need dependency injection here ? Can't we just use `FluentValidation` package ?

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Validators/EmailTemplateValidator .cs
> +            .MaximumLength(256);
Change max length to 129_536

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Validators/SmsTemplateValidator.cs
> +            .WithMessage("Sms template content is required")
I think we don't need custom messages

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Repositories/Interfaces/IEmailTemplateRepository.cs
> +    /// Get all templates which IQuerable
Change comment to "Returns queryable of email templates"

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Repositories/Interfaces/IEmailTemplateRepository.cs
> +    /// Create EmailTemplate async
Don't use "async" keyword

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Repositories/Interfaces/ISmsTemplateRepository.cs
> +        CancellationToken cancellationToken = default);
Update comments just like in email template repository comments

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/Models/Querying/FilterPagination.cs
> +    public uint PageToken { get; set; } = 1;
Add comments

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/appsettings.json
> +  "AirBnBNotificationsDatabaseConnection": "Host=localhost;Port=5433;Database=TrainningAirBnB;Username=postgres;Password=postgres"
Add connection strings inside "ConnectionStrings" section and move connection strings to appsettings.Development.json

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Profiles/SmsTemplateProfile.cs
> +public class SmsTemplateProfile : Profile
Rename to "SmsTemplateMapper", both type and the file

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Profiles/EmailTemplateProfile.cs
> +public class EmailTemplateProfile : Profile
Rename to "EmailTemplateMapper", both type and the file

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Models/DTOs/SmsTemplateDTO.cs
> +public class SmsTemplateDTO
"Dto" as postfix, not "DTO"

2023-11-29 07:46 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Models/DTOs/EmailTemplateDTO.cs
> +public class EmailTemplateDTO
"Dto" as postfix, not "DTO"

2023-11-30 11:54 UTC, botirjonabdumannonovv approved these changes

2023-11-30 12:01 UTC, botirjonabdumannonovv approved these changes

2023-12-04 14:37 UTC, Xolmuratov02 submitted a review, later dismissed

2023-12-06 23:20 UTC, botirjonabdumannonovv submitted a review, later dismissed

2023-12-14 13:34 UTC, sulton-max requested changes

2023-12-14 13:34 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Mappers/UserDto.cs
> +    {
ha public qilish kerak

2023-12-14 13:34 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Validators/EmailTemplateValidator .cs
> +            .MaximumLength(129_536);
Max subject length must be 256

2023-12-21 08:37 UTC, botirjonabdumannonovv submitted a review, later dismissed

2023-12-21 08:37 UTC, botirjonabdumannonovv commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Configurations/HostConfiguration.Extensions.cs
>  using AirBnB.Persistence.Repositories.Interfaces;
remove unnecessary row

2023-12-21 14:22 UTC, Xolmuratov02 submitted a review, later dismissed

2023-12-22 14:42 UTC, sulton-max submitted a review, later dismissed

2023-12-22 16:22 UTC, Xolmuratov02 submitted a review, later dismissed

2023-12-22 21:03 UTC, closed without merging