Create account service
sulton-max/Training.AirBnb.Clone pull request #222
Opened 2023-12-07 00:24 UTC by botirjonabdumannonovv

Closes #207

2023-12-22 13:30 UTC, Xolmuratov02 approved these changes

2023-12-26 15:14 UTC, Xolmuratov02 approved these changes
Honey Code

2023-12-27 16:37 UTC, Ilxom-22 requested changes

2023-12-27 16:37 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Identity/Services/AccountService.cs
> +        if (emailAddress is null)
Bu yerda ham isNullOrWhiteSpace bilan tekshiring.

2023-12-27 16:49 UTC, Ilxom-22 approved these changes

2023-12-28 12:30 UTC, sulton-max requested changes

2023-12-28 12:30 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Identity/Services/AccountService.cs
> +    IdentityDbContext dbContext,
Why we are using `DbContext` directly in high level service ?

2023-12-28 12:30 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Identity/Services/AccountService.cs
> +        return await query.SingleOrDefaultAsync(cancellationToken);
Change to `FirstOrDefaultAsync`

2023-12-28 12:30 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Identity/Services/AccountService.cs
> +        return await user.AnyAsync(cancellationToken);
I think we should set `IsVerified` property to `true` here, no ?

2024-01-06 02:33 UTC, Xolmuratov02 approved these changes

2024-01-14 01:27 UTC, sulton-max approved these changes

2024-01-17 15:21 UTC, closed without merging