Feature/#225 add distributed cache task finished
sulton-max/Training.AirBnb.Clone pull request #224
Opened 2023-12-17 16:08 UTC by bunyodkamalov

2023-12-18 07:21 UTC, sulton-max requested changes
Good job

2023-12-18 07:21 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Repositories/EntityRepositoryBase.cs
> +    private TContext DbContext => dbContext;
Make this protected

2023-12-18 07:21 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Repositories/EntityRepositoryBase.cs
> +    protected async ValueTask<IList<TEntity>> GetAsync(QuerySpecification<TEntity> querySpecification, bool asNoTracking = false,
Add as no tracking to query specification and remove from method parameters

2023-12-18 07:21 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Repositories/EntityRepositoryBase.cs
> +        }
Don't need brackets here

2023-12-18 07:21 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Repositories/EntityRepositoryBase.cs
> +        }
No need for brackets here

2023-12-18 07:21 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Repositories/Interfaces/IUserRepository.cs
> +        CancellationToken cancellationToken = default);
Remove as no tracking

2023-12-18 07:21 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/Identity/Services/IUserService.cs
> +        CancellationToken cancellationToken = default);
Remove as no tracking

2023-12-18 07:21 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Controllers/AccountsController.cs
> +        var result = await userService.GetAsync(specification);
Don't create query specification manually, use `IQueryConvertible` interface method

2023-12-18 07:45 UTC, botirjonabdumannonovv approved these changes

2023-12-18 13:03 UTC, botirjonabdumannonovv submitted a review, later dismissed

2023-12-18 14:38 UTC, sulton-max reviewed
Good just change filter to query inside action

2023-12-19 15:04 UTC, botirjonabdumannonovv approved these changes

2023-12-20 12:11 UTC, sulton-max approved these changes

2023-12-20 12:16 UTC, merged