Feature/#216 create listing entity
sulton-max/Training.AirBnb.Clone pull request #234
Opened 2023-12-19 14:53 UTC by botirjonabdumannonovv

add listing status enum
add listing entity
add Ilisting service interface
add listing dbContext
add listing configuration
add listing validator
add listing repository interface
add listing repository
add listing service
add listing migration
add listing data transfer object (dto)
add listing mapper
register listing to DI
add listing connection string
add listing controller

2023-12-22 14:30 UTC, bunyodkamalov submitted a review, later dismissed

2023-12-22 16:27 UTC, Xolmuratov02 approved these changes

2023-12-22 16:36 UTC, Xolmuratov02 approved these changes

2023-12-23 15:32 UTC, sulton-max requested changes

2023-12-23 15:32 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Entities/Listing.cs
> +}
Add comment

2023-12-23 15:32 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Entities/Money.cs
> +}
Add comment

2023-12-23 15:32 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Enums/Currency.cs
> +}
Add comment

2023-12-23 15:32 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Validators/ListingValidator.cs
> +                .NotEmpty().WithMessage("Price is required.");
Remove message

2023-12-23 15:32 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Entities/Address.cs
> +}
Add comment

2023-12-23 15:32 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Models/DTOs/ListingDto.cs
> +    public DateOnly BuiltDate { get; set; }
Add comment

2023-12-23 15:37 UTC, Xolmuratov02 approved these changes

2023-12-23 15:46 UTC, bunyodkamalov approved these changes

2023-12-25 15:32 UTC, Xolmuratov02 approved these changes
Honey Code))

2023-12-26 11:51 UTC, sulton-max approved these changes

2023-12-26 12:11 UTC, merged