Feature/#214
sulton-max/Training.AirBnb.Clone pull request #245
Opened 2023-12-22 08:52 UTC by abdura52

User settings repository & interface
user settings service  and interface
User settings  validator
userDto model
Mapper
Notification type enum
Theme enum

added

2023-12-22 09:36 UTC, botirjonabdumannonovv submitted a review, later dismissed

2023-12-22 09:36 UTC, botirjonabdumannonovv commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Enums/NotificationType.cs
> +{
NotificationType enumga ham comment yozish kerak edi

2023-12-22 09:36 UTC, botirjonabdumannonovv commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Enums/Theme.cs
> +{
Theme enumga ham comment yozish kerak edi

2023-12-22 14:25 UTC, botirjonabdumannonovv approved these changes

2023-12-22 14:39 UTC, sulton-max requested changes

2023-12-22 14:39 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/Identity/Services/IUserSettingsService.cs
> +public interface IUserSettingsService
Add comment as "Defines user settings foundation service functionalities"

2023-12-22 14:39 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Enums/Theme.cs
> +    Dark = 0,
Add `SystemTheme` as first value, and `Dark` as last value

2023-12-22 14:39 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Validators/UserSettingsValidator.cs
> +        RuleFor(userSettings => userSettings.PreferredTheme).NotEmpty().NotNull();
Remove this

2023-12-22 14:39 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/EntityConfigurations/UserSettingsConfiguration.cs
> +    }
Add as `HasForeignKey<UserSettings>`

2023-12-24 11:25 UTC, botirjonabdumannonovv approved these changes

2023-12-24 11:26 UTC, botirjonabdumannonovv commented
Descriptionga Closes deb branchizni yozib qo'ying

2023-12-25 16:51 UTC, Habiba67y approved these changes

2023-12-26 16:06 UTC, sulton-max approved these changes
Good job

2023-12-26 16:14 UTC, Habiba67y approved these changes

2023-12-26 16:15 UTC, merged