Feature/#226-Site-header
sulton-max/Training.AirBnb.Clone pull request #249
Opened 2023-12-22 23:36 UTC by Ozodbek4

2023-12-23 00:28 UTC, botirjonabdumannonovv requested changes

2023-12-23 00:28 UTC, botirjonabdumannonovv commented on src/Training.AirBnb.Clone.Frontend/src/main.ts
> +createApp(App).mount('#app')
tepadagilarni nimaga remove qilib yubordiz.
ustoz route qo'shganda shuni ham qo'shing degan edi

2023-12-23 14:23 UTC, Xolmuratov02 submitted a review, later dismissed

2023-12-23 17:10 UTC, Xolmuratov02 submitted a review, later dismissed

2023-12-23 17:21 UTC, Abdurahmon0412 approved these changes

2023-12-24 06:23 UTC, Xolmuratov02 requested changes

2023-12-24 06:23 UTC, Xolmuratov02 commented on src/Training.AirBnb.Clone.Frontend/src/infrastructure/services/AppThemeService.ts
> +        const dakMode= localStorage.getItem("darkMode") !== null ? localStorage.getItem("darkMode") == "true" : false;
O'zgaruvchi nomi dak mode bo'lib qolibdi

2023-12-24 11:24 UTC, botirjonabdumannonovv approved these changes

2023-12-25 15:32 UTC, Xolmuratov02 submitted a review, later dismissed

2023-12-26 11:38 UTC, sulton-max requested changes

2023-12-26 11:38 UTC, sulton-max commented on src/Training.AirBnb.Clone.Frontend/index.html
> +    <script type="module" src="/src/main.ts"></script>
Why 2 sources files are added ? Also need to add script as last element of body 
![Uploading Screenshot 2023-12-26 at 16.36.04.png…]()

2023-12-26 11:38 UTC, sulton-max commented on src/Training.AirBnb.Clone.Frontend/src/App.vue
> +  <home-view/>
Remove unnecessary empty space

2023-12-26 11:38 UTC, sulton-max commented on src/Training.AirBnb.Clone.Frontend/src/common/views/HomeView.vue
> +// import LocationsContainer from "@/modules/locations/components/ListingsContainer.vue";
Remove comments

2023-12-26 15:01 UTC, Xolmuratov02 approved these changes

2023-12-26 15:01 UTC, Xolmuratov02 approved these changes

2023-12-26 15:11 UTC, sulton-max approved these changes

2023-12-26 15:11 UTC, merged