Implemented email and sms rendering services
sulton-max/Training.AirBnb.Clone pull request #254
Opened 2023-12-25 14:34 UTC by Habiba67y

2023-12-25 16:13 UTC, abdura52 submitted a review, later dismissed

2023-12-26 12:22 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/Notifications/Models/EmailMessage.cs
> +    public string SendEmailAddress { get; set; } = default!;
Menda ketgan xato birga bir takrorlanibdi ))

2023-12-27 16:48 UTC, Ilxom-22 approved these changes

2023-12-27 16:54 UTC, botirjonabdumannonovv approved these changes

2023-12-28 18:03 UTC, sulton-max requested changes

2023-12-28 18:18 UTC, Habiba67y commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Notifications/Services/EmailRenderingService.cs
> +public class EmailRenderingService(
to the interface?

2023-12-29 03:37 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Notifications/Services/EmailRenderingService.cs
> +public class EmailRenderingService(
Nope, to the implementation

2023-12-29 11:04 UTC, Habiba67y commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Notifications/Services/EmailRenderingService.cs
> +public class EmailRenderingService(
oh sorry, I'll fix it

2023-12-29 15:40 UTC, sulton-max approved these changes

2023-12-29 17:08 UTC, Ilxom-22 approved these changes

2024-01-14 01:27 UTC, sulton-max approved these changes

2024-01-14 01:29 UTC, merged