Fix/#211 Listing Category entity
sulton-max/Training.AirBnb.Clone pull request #265
Opened 2023-12-27 16:11 UTC by Ilxom-22

2023-12-27 17:00 UTC, botirjonabdumannonovv approved these changes

2023-12-29 15:26 UTC, sulton-max requested changes

2023-12-29 15:26 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Extensions/DbContextExtensions.cs
> +        matchingConfigurationTypes.ForEach(type => modelBuilder.ApplyConfiguration((dynamic)Activator.CreateInstance(type)!));
Break this into 

- `GetEntityTypes` - method that returns types of all `DbSet` members in `IList` collection
- `GetEntityConfigurations - method that calls `GetEntityTypes` internally and returns `IList` of configuration types
- finally original `ApplyEntityConfigurations` that calls `GetEntityConfigurations` internally and applies all configurations

2024-01-14 01:14 UTC, sulton-max approved these changes

2024-01-14 16:11 UTC, rashidovasadbek approved these changes

2024-01-14 16:15 UTC, merged