Feature/#19
sulton-max/Training.AirBnb.Clone pull request #27
Opened 2023-09-24 11:14 UTC by Abdurahmon0412

2023-09-24 11:17 UTC, boburjon1504 approved these changes

2023-09-24 13:05 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/Reservation.cs
> +            TotalPrice = totalPrice;
Constructorda createdDate qo'yilmabti. O'zini Id si ham qo'yilmagan.

2023-09-24 13:07 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +        {
Reservation tipida ma'lumot kirib kevotkanda o'zgaruvchi nomi entity bo'lishi shartmas. O'ziz uni reservation deb o'zgartirsez bo'ladi. Bu entity deb yozganimni sababi generic interface bo'lganligi uchun. Lekin siz nomlarini hohlaganingizcha o'zgartirsez bo'ladi. Bu hato emas shunchaki comment.

2023-09-24 13:10 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +                return false;
StartDate faqat default holatiga mas bugungi holatiga ham tekshirilishi kerak. Chunki user otib ketkan kun uchun reservation yarata olmasligi kerak.

2023-09-24 13:11 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +                return false;
EndData ham faqat defaultga emas balki bugungi kundan va start date dan keyin ekanligini ham validatsiya qilish kerak.

2023-09-24 13:13 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +            return true;
TotalPrice faqat decimal ekanligiga tekshirishni hojati yo'q chunki decimaldan boshqa tipdagi object kirib kelishini iloji yoq. Undan ko'ra 0 dan baland ekanligiga tekshirish kerak.

2023-09-24 13:15 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +            await _appDataContext.Reservations.SaveChangesAsync();
saveChanges true bo'lgan holatdagina filega saqlash kerak boshqa holda saqlash kerak emas. Shunga etiborli bo'ling.

2023-09-24 13:16 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +                throw new ArgumentNullException();
ArgumentNullException() dan ko'ra ReservationNotFound() exception yaratib shuni throw qilganingiz manoliroq bo'ladi. Domain folderda ReservationNotFound() exception yarating va shuni throw qiling.

2023-09-24 13:17 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +                throw new ArgumentNullException();
Bu yerda ham ReservationNotFound Exception throw qilish kerak.

2023-09-24 13:17 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +            await _appDataContext.Reservations.SaveChangesAsync();
saveChanges true bo'lgandagina file saqlanishi kerak.

2023-09-24 13:18 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +                throw new ArgumentNullException("Reservation not found");
Bu yerda ham manoliroq exception throw qilish kerak.

2023-09-24 13:19 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +
Bu yerda modifiedDate propertyga qiymat berilish esingizdan chiqibti.

2023-09-24 13:19 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +            return new ValueTask<Reservation>(foundReseervation);
saveChanges true bo'lsagina filega saqlanishi kerak.

2023-09-24 13:21 UTC, Ilxom-22 requested changes
Hatoliklar bor. Har bitta kod tagiga comment yozilgan. Shularni to'g'irlang.

2023-09-25 06:46 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +                return false;
Nega totalPrice 0 dan kotta bo'lsa false qaytarvordiz? TotalPrice bu arendaga olinvotgan joyni umumiy narxi necha pulga tushvotkanini bildiradigan property. Agar u noldan kotta bo'lgan holda false qaytsa hamma uylar tekinga berilishi kerak bo'lib qoladi.

2023-09-25 06:47 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +            var amountDate = startDate - DateTime.UtcNow;
Bu yerdan amoundDate o'zgaruvchisi hechqayerda ishlatilmagan. Buni o'chirib yuborish kerak.

2023-09-25 06:50 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ReservationService.cs
> +                throw new ReservationUpdateExeption("Reservation not found or invalid Id");
Bu yerda ReservationNotFound exception ishlatsa ham bo'lar edi. Chunki update qilish holatida hech qanday muammo bo'lgani yo'q. Berilgan reservation topilmadi holos.

2023-09-25 06:54 UTC, Ilxom-22 requested changes
Yana 2 - 3 ta hatoliklar bor. Shularni ham to'g'irlab qo'ying.

2023-09-26 05:51 UTC, Abdurahmon0412 commented
GetUndeleted methodi qo'shildi 
uni Createni ichidaham ishlatib qo'ydim chunki yani bittanarsani o'chirib tashlab yana yangi qo'sha olishi uchun

2023-09-26 10:48 UTC, Ilxom-22 approved these changes

2023-09-26 10:55 UTC, rashidovasadbek approved these changes

2023-09-26 10:55 UTC, merged