Feature/#227 Listings Category Tab Component
sulton-max/Training.AirBnb.Clone pull request #270
Opened 2023-12-29 16:24 UTC by Ilxom-22

2024-01-18 07:50 UTC, sulton-max requested changes

2024-01-18 07:50 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Configurations/HostConfiguration.cs
> +            .AddCors();
must be added before exposers, otherwise won't work

2024-01-18 07:50 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Configurations/HostConfiguration.Extensions.cs
> +            policy => policy.WithOrigins("http://localhost:5173")
Need to write to external configuration

2024-01-18 11:33 UTC, sulton-max submitted a review, later dismissed
Good job

2024-01-18 11:58 UTC, rashidovasadbek approved these changes

2024-01-19 14:52 UTC, Jasurbek1223 approved these changes

2024-01-19 14:53 UTC, merged