Updated two properties which are ReceiverPhoneNumber from ReceiverAdd…
sulton-max/Training.AirBnb.Clone pull request #285
Opened 2024-01-23 12:26 UTC by Mirzohid-Mominov

…ress and SenderPhoneNumber from SenderAddress

2024-01-24 07:07 UTC, Mirzohid-Mominov commented
Closed #199

2024-01-24 13:40 UTC, sulton-max requested changes

2024-01-24 13:40 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Notifications/Brokers/SmtpEmailSenderBroker.cs
> +    }
Use primary constructor

2024-01-26 06:54 UTC, Mirzohid-Mominov commented
closes #199

2024-01-26 12:17 UTC, sulton-max requested changes

2024-01-30 13:11 UTC, Mirzohid-Mominov commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Notifications/Services/EmailSenderService.cs
> +            }
optimized SendAsync method

2024-01-31 07:52 UTC, Mirzohid-Mominov commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Notifications/Services/EmailSenderService.cs
> +            }
done

2024-01-31 11:18 UTC, sulton-max submitted a review, later dismissed
Good job

2024-02-01 07:47 UTC, Abdurasulovich reviewed
Done

2024-02-01 10:24 UTC, rashidovasadbek approved these changes

2024-02-01 10:45 UTC, Ilxom-22 approved these changes

2024-02-01 10:45 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Notifications/Services/SmsSenderService.cs
> +    }
SmsMessageValidator inject qilingan lekin ishlatilmagan. SmsMessageni validatsiya qilmasdan send qilingan.

2024-02-01 10:48 UTC, Ilxom-22 requested changes

2024-02-01 10:48 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Notifications/Services/SmsSenderService.cs
> +        return  false;
SmsMessageValidator inject qilingan lekin ishlatilmagan. SmsMessageni validatsiya qilmasdan send qilingan.

2024-02-01 12:08 UTC, Mirzohid-Mominov commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Notifications/Services/SmsSenderService.cs
> +        return  false;
done

2024-02-01 21:56 UTC, rashidovasadbek approved these changes

2024-02-02 02:58 UTC, Ilxom-22 approved these changes

2024-02-02 02:58 UTC, merged