Feature/#13
sulton-max/Training.AirBnb.Clone pull request #29
Opened 2023-09-25 06:05 UTC by rashidovasadbek

2023-09-25 06:10 UTC, Abdurahmon0412 approved these changes

2023-09-25 06:59 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/EmailTemplateService.cs
> +            throw new EmailTemplateException("EmailTemplate not found");
EmailTemplateNotFound exception throw qilsa tushunarliroq bo'ladi.

2023-09-25 07:01 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/EmailTemplateService.cs
> +
Modified Date propertyga qiymat berilmagan. ModifiedDate property SoftDeletedEntity dan keladi. Object o'zgartirilganda uni o'zgartirilgan vaqtini ModifiedDate ga qiymat qilib berish kerak.

2023-09-25 07:02 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/EmailTemplateService.cs
> +        await _dataContext.SaveChangesAsync();
saveChanges true bo'lgan holatdagina filega saqlashi kerak. Sizda har qanday holda filega saqlab qo'yvotti.

2023-09-25 07:04 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/EmailTemplateService.cs
> +            throw new EmailTemplateException("You searched emailTemplate not found");
Bu yerda ham EmailTemplateNotFound exception throw qilgan manoliroq bo'ladi. foundemailTemplate emas foundEmailTemplate qilib nomlang o'zgaruvchilarni.

2023-09-25 07:05 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/EmailTemplateService.cs
> +        foundemailTemplate.IsDeleted = true;
DeletedDate propertyga qiymat berilmaga.

2023-09-25 07:07 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/EmailTemplateService.cs
> +        await _dataContext.SaveChangesAsync();
saveChanges o'zgaruvchisidan false kelib qolishi mumkinligiga etibor bermagansiz. saveChanges true bo'lgan holatdagina filega saqlang. Keyin deyarli hamma yoqda _dataContext.SaveChangesAsync() ishlatibsiz. Shuni _dataContext.EmailTemplates.SaveChangesAsync() ga o'zgartirib chiqing. Bularni o'rtasida farq bor.

2023-09-25 07:08 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/EmailTemplateService.cs
> +    {
Bu method ichida ham oldingi hatoliklar takrorlangan. Shularni hammasini to'g'irlang.

2023-09-25 07:09 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Persistance/DataContexts/AppFileContext.cs
> +    #endregion
Mana shuni iloji bo'lsa constructordan tepaga yozganingiz maqul.

2023-09-25 07:14 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/EmailTemplate.cs
> +    {
Id tashqaridan kirib kelishi kerak emas. Guid bo'lganligi uchun uni constructor ichida generate qilib qo'ysa bo'ladi. Agar tashqaridan id kirib keladigan bo'lsa uni validatsiya qilishga to'g'ri kelib qoladi.

2023-09-25 07:16 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/EmailTemplateService.cs
> +        await _dataContext.EmailTemplates.AddAsync(emailTemplate);
Validatsiya qilmasdan har qanday objectni qo'shib qo'ygansiz. Subject, body va Id ni validatsiya qiladigan method yozing va shuni ishlating.

2023-09-25 07:17 UTC, Ilxom-22 requested changes
Hatoliklar bor. To'g'irlab qayta pull request tashlang.

2023-09-26 14:18 UTC, Ilxom-22 approved these changes

2023-09-26 16:32 UTC, Abdurahmon0412 approved these changes

2023-09-26 16:33 UTC, Abdurahmon0412 approved these changes

2023-09-26 16:34 UTC, merged