Create sign-up / sign-in modal
sulton-max/Training.AirBnb.Clone pull request #292
Opened 2024-01-25 17:00 UTC by Ilxom-22

Closes #238

2024-01-28 17:57 UTC, sulton-max requested changes

2024-01-28 17:57 UTC, sulton-max commented on src/Training.AirBnb.Clone.Frontend/src/App.vue
> +  <sign-in-up-modal :modal-active="modalActive" @close-modal="toggleModal"/>
As we are teleporting `SignInUpModal` to body, why not add it to `MainHeader` component ?

2024-01-28 17:57 UTC, sulton-max commented on src/Training.AirBnb.Clone.Frontend/src/Modules/locations/components/SignInUpModal.vue
> +        <div class="relative h-auto mx-auto my-8 border-2 sm:w-full md:w-[570px] lg:w-[570px] xl:w-[570px] theme-bg-secondary theme-border rounded-xl" @click.stop>
Isn't adding md:w-[570px] enough here ?

2024-01-28 17:57 UTC, sulton-max commented on src/Training.AirBnb.Clone.Frontend/src/Modules/locations/components/EmailPhoneInput.vue
> +})
I think comparing old and new values is unnecessary here, just pass expression body

2024-02-01 02:40 UTC, sulton-max requested changes

2024-02-01 02:40 UTC, sulton-max commented on src/Training.AirBnb.Clone.Frontend/src/common/components/MainHeader.vue
> +  }
Can we move this to `DocumentService` too ?

2024-02-01 02:40 UTC, sulton-max commented on src/Training.AirBnb.Clone.Frontend/src/Modules/locations/components/EmailPhoneInput.vue
> +        <h3 class="text-[#797979] text-[12px]">{{ byEmail ? 'Email' : 'Phone number' }}</h3>
Add colors to tailwind configuration

2024-02-01 10:16 UTC, rashidovasadbek approved these changes

2024-02-01 17:43 UTC, sulton-max approved these changes
Looks good to me

2024-02-01 21:59 UTC, rashidovasadbek approved these changes

2024-02-01 21:59 UTC, merged