Create AuthService
sulton-max/Training.AirBnb.Clone pull request #295
Opened 2024-01-26 07:19 UTC by rashidovasadbek

Closes #208

2024-01-26 12:02 UTC, sulton-max requested changes

2024-01-26 15:55 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Entities/User.cs
> +    public IList<UserRole> Roles { get; set; }
Reference - https://github.com/WoW-2-0/Backend.ILA.DataAccess/tree/main/src/EntityConfiguration.ManyToMany.DirectNavigation

2024-02-01 07:53 UTC, Abdurasulovich reviewed
Done fine

2024-02-02 14:42 UTC, sulton-max requested changes

2024-02-02 14:42 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Identity/Services/RoleProcessingService.cs
> +        appDbContext.Roles.Remove(selectedRole);
Why we are removing role from db context ? We need to remove it from user.Roles

2024-02-04 05:03 UTC, Ilxom-22 requested changes

2024-02-04 11:26 UTC, sulton-max approved these changes
Looks good to me

2024-02-04 11:42 UTC, sulton-max approved these changes

2024-02-04 11:44 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/Identity/Models/SignUpDetails.cs
> +    public int Age { get; set; }
Yes, that would be actually correct, let's change that when implementing host sign up, we can close this for now

2024-02-04 12:21 UTC, abdurakh approved these changes
Done ✅

2024-02-04 13:19 UTC, Ilxom-22 approved these changes

2024-02-04 14:08 UTC, merged