Add common CQRS infrastructure
sulton-max/Training.AirBnb.Clone pull request #296
Opened 2024-01-26 07:23 UTC by rashidovasadbek

Closes #278

2024-01-26 11:03 UTC, sulton-max requested changes

2024-01-26 11:03 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/EventBus/IEvenBusBroker.cs
> +    ValueTask SubscribeAsync<TEvent, TEventHandler>() where TEvent : IEvent where TEventHandler : IEventHandler<TEvent>;
Remove subscriber method, create `EventSubscriber` generic service

2024-01-30 04:32 UTC, Ilxom-22 approved these changes

2024-01-30 18:10 UTC, sulton-max requested changes

2024-01-30 18:10 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/EventBus/Brokers/IEventSubscriber.cs
> +}
Add comments

2024-01-30 18:10 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/EventBus/Brokers/IEvenBusBroker.cs
> +    ValueTask PublishAsync<TEvent>(TEvent @event, string exchange, string routingKey, CancellationToken cancellationToken) where TEvent : Event;
Add `PublishLocalAsync` which should send events to MediatR

2024-01-30 18:10 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Application/Common/EventBus/Brokers/IRabbitMqConnectionProvider.cs
> +    /// </remarks>
Remove this

2024-01-30 18:10 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Settings/NotificationSubscriberSettings.cs
> +}
Do we need this in this task ?

2024-01-30 18:44 UTC, sulton-max approved these changes
Good job

2024-01-31 04:11 UTC, botirjonabdumannonovv approved these changes

2024-01-31 04:19 UTC, Ilxom-22 approved these changes

2024-01-31 04:26 UTC, merged