Create menu component and profile button
sulton-max/Training.AirBnb.Clone pull request #297
Opened 2024-01-30 08:22 UTC by Abdurasulovich

2024-01-30 10:07 UTC, Ilxom-22 requested changes

2024-01-30 10:07 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Frontend/src/Modules/profile/components/Darkmode.vue
> +  </div>
Toggle ga transition berib qo'ying. Silliq harakatlanishi uchun.

2024-01-30 10:07 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Frontend/src/Modules/profile/components/ProfileMenuComponent.vue
> +    </button>
Buttonlar hover bo'lganda background rangi o'zgarmayabti.

2024-01-31 10:12 UTC, sulton-max reviewed
Good job

2024-01-31 10:12 UTC, sulton-max commented on src/Training.AirBnb.Clone.Frontend/src/Modules/profile/components/Darkmode.vue
> +    <div  :class="modelValue ? 'translate-x-4' : 'translate-x-0'" class="w-4 h-4 primary-transition-toggle bg-textSecondary rounded-full theme-shadow"></div>
- rename this component to `DarkModeToggler`
- remove toggle value as it uses `AppThemeService` service internally

2024-02-01 04:29 UTC, sulton-max requested changes

2024-02-01 04:29 UTC, sulton-max commented on src/Training.AirBnb.Clone.Frontend/src/Modules/profile/components/ProfileMenuComponent.vue
> +const emit = defineEmits(['update:value', 'onClose']);
Remove props and update emit, as this is not input component

2024-02-04 11:33 UTC, Abdurasulovich reviewed
Fine

2024-02-05 08:49 UTC, Abdurasulovich reviewed
Done

2024-02-05 20:06 UTC, sulton-max approved these changes
Good job

2024-02-07 12:53 UTC, Ilxom-22 approved these changes

2024-02-07 13:31 UTC, sulton-max approved these changes
Well done

2024-02-07 13:31 UTC, merged