Feature/#209
sulton-max/Training.AirBnb.Clone pull request #298
Opened 2024-01-30 13:16 UTC by Mirzohid-Mominov

closes #209

2024-01-30 18:42 UTC, sulton-max requested changes

2024-01-30 18:42 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/DataContexts/AppDbContext.cs
> +
Remove it, as `UserCredentials` isn't a separate entity

2024-01-30 18:42 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Persistence/Migrations/20240130111752_Add_UserCredentials.cs
> +        }
`UserCredentials` is added as separate table here, need to re-generate migrations

2024-01-30 18:42 UTC, sulton-max commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Validators/UserValidator.cs
> -                    .Matches(validationSettingsValue.PasswordRegexPattern);
Move this to `UserCredentialsValidator`

2024-01-31 07:49 UTC, Mirzohid-Mominov commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Validators/UserValidator.cs
> -                    .Matches(validationSettingsValue.PasswordRegexPattern);
done

2024-02-01 07:42 UTC, Abdurasulovich reviewed
Done

2024-02-01 21:48 UTC, rashidovasadbek commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Entities/User.cs
> +
you need to write a comment

2024-02-02 03:16 UTC, Ilxom-22 requested changes

2024-02-02 03:16 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Validators/UserCredentialsValidator.cs
> +                    .Matches(validationSettingsValue.PasswordRegexPattern);
Do we really need to validate hashed password?

2024-02-02 12:25 UTC, Mirzohid-Mominov commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Entities/User.cs
> +
I think it's not mine

2024-02-02 12:25 UTC, Mirzohid-Mominov commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Data/SeedDataExtensions.cs
> +                PasswordHash = data.Internet.Password(8)
got it

2024-02-02 12:29 UTC, Mirzohid-Mominov commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Data/SeedDataExtensions.cs
> +                PasswordHash = data.Internet.Password(8)
it's hashed we did with teacher

2024-02-05 21:16 UTC, sulton-max approved these changes
Looks good to me

2024-02-05 21:28 UTC, Abdurasulovich reviewed
Done

2024-02-06 12:16 UTC, Ilxom-22 approved these changes

2024-02-06 12:16 UTC, merged