Create NotificationHistory entity/repository/service
sulton-max/Training.AirBnb.Clone pull request #300
Opened 2024-02-01 10:39 UTC by abdurakh

closes #202

2024-02-01 10:56 UTC, Abdurasulovich reviewed
Done 👍

2024-02-01 11:06 UTC, Ilxom-22 requested changes

2024-02-01 11:06 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Notifications/Services/EmailHistoryService.cs
> +        var validationResult = emailHistoryValidator.Validate(emailHistory);
Use validation with IncludeRuleSets to specify the rule set to avoid the usage of default validation.

2024-02-01 11:06 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Notifications/Services/SmsHistoryService.cs
> +        var validationResult = smsHistoryValidator.Validate(smsHistory);
Use validation with IncludeRuleSets to specify the rule set to avoid the usage of default validation.

2024-02-01 21:41 UTC, rashidovasadbek approved these changes

2024-02-02 02:55 UTC, Ilxom-22 submitted a review, later dismissed

2024-02-04 03:22 UTC, Ilxom-22 approved these changes

2024-02-04 04:12 UTC, merged