User model and it's CRUD service has been created
sulton-max/Training.AirBnb.Clone pull request #31
Opened 2023-09-25 07:07 UTC by boburjon1504

2023-09-25 07:24 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/User.cs
> +        Id = id
Id tashqaridan kirib kelishi kerak emas. Uni constructor ichida berasiz.

2023-09-25 07:26 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/UserService.cs
> +    {
User tipida kirib kelayotgan object nomi entity bo'lishi shart emas. Uni user deb o'zgartirsangiz bo'ladi o'zingizga tushunarli bo'lishi uchun. Entity nomi shunchaki generic interface dan kelyabti. Uni hohlagancha o'zgartirishingiz mumkin.

2023-09-25 07:27 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/UserService.cs
> +            throw new FormatException("Invalid last name");
FirstName ni 2 marta validatsiya qilgansiz.

2023-09-25 07:29 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/UserService.cs
> +            throw new InvalidOperationException("User not found");
Shu yerda yangi UserNotFound exception throw qilsa bo'ladi. Domain folder da Exceptions folder ichida yangi exception yaratsangiz bo'ladi.

2023-09-25 07:31 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/UserService.cs
> +    {
Bu method ichida ham oldingi hatoliklar takrorlangan shularni to'g'irlab qo'ying.

2023-09-25 07:37 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/UserService.cs
> +        updatedUser.ModifiedDate = DateTimeOffset.UtcNow;
Update qilinvotkanda kirib kelayotgan objectni validatsiya qilish kerak. PhoneNumberId va IsActive propertylari update bo'lmay qolgan. Menimcha emailAddress Update qilish imkoni bo'lmasligi kerak. Chunki email o'zgartirgandan ko'ra yangi account ochilgani yaxshi.

2023-09-25 07:39 UTC, Ilxom-22 requested changes
Umuman olganda yaxshi. Ozgina hatoliklarni to'g'irlab qayta PR qiling. Takrorlangan hatoliklarni bittama bitta yozib o'tirmadim.

2023-09-25 13:17 UTC, rashidovasadbek approved these changes

2023-09-25 13:17 UTC, merged

2023-09-26 07:55 UTC, Abdurahmon0412 commented
thsi is commet