Added refresh token
sulton-max/Training.AirBnb.Clone pull request #319
Opened 2024-02-13 15:46 UTC by Habiba67y

2024-02-16 18:09 UTC, Abdurasulovich reviewed
Done

2024-02-16 18:10 UTC, sulton-max submitted a review, later dismissed
Looks good to me

2024-02-17 08:18 UTC, Ilxom-22 requested changes

2024-02-17 08:18 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Models/DTOs/IdentityTokenDto.cs
> +}
Comments needed here

2024-02-17 08:35 UTC, Habiba67y commented on src/Training.AirBnb.Clone.Backend/AirBnB.Domain/Extension/ExceptionExtensions.cs
> +    }
aha, got it

2024-02-17 08:35 UTC, Habiba67y commented on src/Training.AirBnb.Clone.Backend/AirBnB.Api/Models/DTOs/IdentityTokenDto.cs
> +}
ok

2024-02-17 17:15 UTC, Ilxom-22 approved these changes

2024-02-17 17:15 UTC, merged