Feature/#32
sulton-max/Training.AirBnb.Clone pull request #35
Opened 2023-09-26 12:28 UTC by mexroj0804

2023-09-26 13:13 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/ListingReview.cs
> +            CreatedDate = DateTimeOffset.Now;
CreatedDate uchun DateTimeOffset.Now emas DateTimeOffset.UtcNow ishlatish kerak.

2023-09-26 13:18 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingReviewService.cs
> +
Validatsiya uchun alohida private method yaratib usha yerdan bool qaytarish kerak. CreateAsync methodi ichida shu methoddan foydalangan afzal. Single responsibility ga to'g'ri kelmay qolgan.

2023-09-26 13:26 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingReviewService.cs
> +            if (string.IsNullOrWhiteSpace(listingReview.Comment) || listingReview.Comment.Length < 1000)
listingReview.Comment.Length 1000 dan kam bo'lsa exception throw qilingan. Yani agar comment 1000 ta characterdan kam bo'lsa demak valid emas. Aslida huddi shuni teskarisi bo'lishi kerak.  Comment characteri 1000 tadan ko'p bo'lsa exception throw qilinishi kerak.

2023-09-26 13:26 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingReviewService.cs
> +
Barcha validatsiyalarni alohida methodga ajrating.

2023-09-26 13:28 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingReviewService.cs
> +
update qilinvotkanda writtenBy va listingId o'zgarib ketishi (update qilinishi) mumkin emas.

2023-09-26 13:32 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingReviewService.cs
> +                throw new ListingReviewNotFoundException("ListingReview not found!"));
GetById qilinganda _appDataContext.ListingReviews ichidan qidirilsa delete bo'lib ketkan objectlarni ham qaytarish ehtimoli bor. Shuning uchun GetUndeletedListingReviews ichidan qidirib qaytarish kerak.

2023-09-26 13:32 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingReviewService.cs
> +            return new ValueTask<ICollection<ListingReview>>(listigReviews.ToList());
_appDataContext.ListingReviews ichidan qidirilsa delete bo'lib ketkan objectlarni ham qaytarish ehtimoli bor. Shuning uchun GetUndeletedListingReviews ichidan qidirib qaytarish kerak.

2023-09-26 13:32 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingReviewService.cs
> +        }
_appDataContext.ListingReviews ichidan qidirilsa delete bo'lib ketkan objectlarni ham qaytarish ehtimoli bor. Shuning uchun GetUndeletedListingReviews ichidan qidirib qaytarish kerak.

2023-09-26 13:38 UTC, Ilxom-22 requested changes
Hatoliklar bor.

2023-09-27 04:49 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingReviewService.cs
> +                await _appDataContext.SaveChangesAsync();
await _appDataContext.SaveChangesAsync();
mana shuni appDataContext.(usizni qo'shgan modelizni nomiqo'yganiz yahshi)SaveChangesAsync();

2023-09-27 04:49 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingReviewService.cs
> +                await _appDataContext.SaveChangesAsync();
appdatani emas uzizni modelizni savechanges qilasiz

2023-09-27 04:49 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingReviewService.cs
> +                await _appDataContext.SaveChangesAsync();
bu yerdaham uzizni modelizni savechanges qilganiz yaxshi

2023-09-28 01:51 UTC, Ilxom-22 requested changes
Validatsiyani assinxron emas sinxron qilib qo'ying. Qolgani yaxshi.

2023-09-28 07:52 UTC, Ilxom-22 approved these changes

2023-09-28 13:43 UTC, Abdurahmon0412 submitted a review, later dismissed
Exceptionda defoult constructor yozib ketgan yaxshi chunki Messagesizham exception otish mumkin

2023-09-28 13:46 UTC, Ilxom-22 approved these changes

2023-09-28 13:47 UTC, Abdurahmon0412 approved these changes

2023-09-28 13:47 UTC, merged