#34
sulton-max/Training.AirBnb.Clone pull request #42
Opened 2023-09-27 09:55 UTC by mexroj0804

2023-09-28 01:58 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/Address.cs
> +        public string Province { get; set; }
Province nullable bo'lishi kerak.

2023-09-28 01:59 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/Address.cs
> +        public string? AddressLine1 { get; set; }
AddressLine1 nullable bo'lishi mumkin emas. Chunki eng kamida 1 ta address bo'lishi kerak. Qolganlari optional. Hozirgi holatda address berish hammasi optional bo'lib qolgan.

2023-09-28 02:04 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/AddressService.cs
> +        private IQueryable<Address> GetUndelatedAddresses() => _appDataContext.Addresses
Shu method nomini hamma Abdurahmondan ko'chirvotti shekilli, hammasini nomida birxil hatolik ketgan. GetUndeletedAddresses yoki GetActiveAddresses deb nomlasangiz yaxshi bo'ladi.

2023-09-28 02:06 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/AddressService.cs
> +            updatedAddress.ModifiedDate = DateTimeOffset.UtcNow;
Addressni city yoki country o'zgarishi mumkin. Update qilinvotkanda cityId va countryId ni ham update qiling.

2023-09-28 02:07 UTC, Ilxom-22 requested changes
Hatoliklari bor.

2023-09-29 10:12 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/AddressService.cs
> +
CityService va Country service ni interface bilan qabul qilish kerak, yani EntityBaseService<CityService> va EntityBaseService<CountryService> orqali, bo'lmasam classni o'ziga bog'lanib qoladi.

2023-09-29 10:17 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/AddressService.cs
> +        {
Shu method nomini to'g'irlash kerak, chunki bu method unique likka tekshirmaydi, city country ga tegishli ekanligini tekshiradi, shunga mos nom qo'yish kerak.

2023-09-29 10:19 UTC, Ilxom-22 requested changes
Hatoliklar bor.

2023-09-29 17:00 UTC, Ilxom-22 approved these changes

2023-09-29 17:02 UTC, Abdurahmon0412 approved these changes

2023-09-29 17:06 UTC, rashidovasadbek approved these changes

2023-09-29 17:08 UTC, rashidovasadbek approved these changes

2023-09-29 17:08 UTC, Ilxom-22 approved these changes

2023-09-29 17:08 UTC, merged