#41
sulton-max/Training.AirBnb.Clone pull request #43
Opened 2023-09-28 06:06 UTC by mexroj0804

2023-09-28 09:39 UTC, Ilxom-22 approved these changes

2023-09-28 09:42 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingRatingService.cs
> +
Create qilinvotkanda huddi shu listing uchun 2 ta rating bo'lib qolmasligini oldini olish kerak. Yani yangi rating kirib kelayotganda unda qaysi listing uchun ekanligi haqida id bo'ladi. Huddi shu id uchun boshqa rating bor bo'lsa yangi rating qo'shilishi kerak emas.

2023-09-28 09:42 UTC, Ilxom-22 requested changes
Bitta hato bor.

2023-09-29 03:53 UTC, Abdurahmon0412 submitted a review, later dismissed
Exception yaratilayotganda defoult contryctor bo'lgani yahshiroq chunki 
messagesizham exception otishi mumkinda

2023-09-29 10:06 UTC, Ilxom-22 submitted a review, later dismissed

2023-09-29 17:03 UTC, Ilxom-22 approved these changes

2023-09-29 17:14 UTC, Abdurahmon0412 approved these changes

2023-09-29 17:17 UTC, Ilxom-22 approved these changes

2023-09-29 17:17 UTC, boburjon1504 approved these changes

2023-09-29 17:17 UTC, merged