Feature/#40 ListingOccupancyModel
sulton-max/Training.AirBnb.Clone pull request #44
Opened 2023-09-28 06:30 UTC by Abdurahmon0412

2023-09-28 08:26 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingOccupancyService.cs
> +            return true;
adults 0 dan kichkina bo'lganda emas 1 dan kam bo'lganda false qaytarish kerak. Chunki eng kamida 1 ta katta odam kelishi kerak, voyaga yetmagan bollarni jonatib yuborishi noto'g'ri. Qogan validatsiyani Listing tayyor bo'lgandan keyin o'zgartiramiz.

2023-09-28 08:28 UTC, Ilxom-22 requested changes
Hozircha merge qilib tursak bo'ladi. Lekin validatsiya uchun listingService kerak bo'lar ekan. Listing service tayyor bo'lganidan keyin validatsiya biroz o'zgaradi.

2023-09-28 08:30 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Services/ListingOccupancyService.cs
> +            return true;
Model nomini ham Occupancy deb nomlab qo'yish kerak chunki listing occupancy uchun alohida model yaratilishi kerak ekan, va u yerda biroz boshqacharoq ma'lumotlar bo'ladi.

2023-09-29 16:49 UTC, Ilxom-22 approved these changes

2023-09-29 17:02 UTC, boburjon1504 approved these changes

2023-09-29 17:05 UTC, Ilxom-22 approved these changes

2023-09-29 17:05 UTC, merged