Feature/#63/asadbek
sulton-max/Training.AirBnb.Clone pull request #65
Opened 2023-09-30 14:17 UTC by rashidovasadbek

2023-09-30 15:00 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/NotificationsServices/EmailPlaceholderService.cs
>      {
Propertylardan keyin va constructordan oldin ham bitta bo'sh line qoldirish kerak.

2023-09-30 15:01 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/NotificationsServices/EmailPlaceholderService.cs
> +namespace Backend_Project.Infrastructure.Services.NotificationsServices;
Namespace va class o'rtasida ham bitta bo'sh line bo'lishi kerak.

2023-09-30 15:02 UTC, Ilxom-22 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/NotificationsServices/EmailService.cs
>      public EmailService(IDataContext dataContext, IValidationService validationService)
Propertylar var constructor o'rtasida bitta bo'sh line bo'lishi kerak.

2023-09-30 15:04 UTC, Ilxom-22 requested changes
Bir ikkita joyiga qarab qo'ying.

2023-10-02 02:44 UTC, Abdurahmon0412 requested changes

2023-10-02 02:44 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/NotificationsServices/EmailService.cs
>          throw new NotImplementedException();
shuni o'rniga o'zimizni custom exceptionimiz yaxshi emasmi

2023-10-02 02:45 UTC, Abdurahmon0412 submitted a review, later dismissed

2023-10-02 12:59 UTC, Abdurahmon0412 submitted a review, later dismissed

2023-10-02 13:10 UTC, Xolmuratov02 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Application/Interfaces/IEmailPlaceholderService.cs
>      ValueTask<Dictionary<string, string>> GEtTemplateValues(Guid userId,EmailTemplate emailTemplate);
Guid userId dan kn probel qolib ketibdi

2023-10-02 13:11 UTC, Xolmuratov02 reviewed
Probellar tushib qolibdi

2023-10-02 13:12 UTC, Abdurahmon0412 approved these changes

2023-10-03 02:59 UTC, Abdurahmon0412 approved these changes

2023-10-03 08:46 UTC, Xolmuratov02 approved these changes

2023-10-03 12:03 UTC, Abdurahmon0412 approved these changes

2023-10-03 12:04 UTC, merged