Fix/#63/abdurahmon/Refactor
sulton-max/Training.AirBnb.Clone pull request #81
Opened 2023-10-01 08:42 UTC by Abdurahmon0412

2023-10-02 08:16 UTC, Ilxom-22 requested changes
Sonar cloud check digan narsa qoshganla ustoz kodi tekshirib beradigan. Shu error bervotti to'g'irlab qo'ying. Keyin PR main ga ketib qobti.

2023-10-02 13:18 UTC, Xolmuratov02 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/Amenity.cs
> +    public Amenity(string amenityName, Guid categoryid)
naming: "categoryId"

2023-10-02 13:18 UTC, Xolmuratov02 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/City.cs
> +        public Guid CountryId { get; set; }
Construktorni propertylardan ajratib qoyish kk

2023-10-02 13:19 UTC, Xolmuratov02 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/Country.cs
> +        public int RegionPhoneNumberLength { get; set; }
Construktorni propertylardan ajratib qoyish kk

2023-10-02 13:19 UTC, Xolmuratov02 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/Country.cs
> +        public int RegionPhoneNumberLength { get; set; }
Construktorni propertylardan ajratib qoyish kk

2023-10-02 13:20 UTC, Xolmuratov02 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/EmailTemplate.cs
> +    public override int GetHashCode()
return ni =>  ga 6zgartirsa ham b6ladi

2023-10-02 13:21 UTC, Xolmuratov02 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/ListingCategory.cs
> +
B6sh joy va qator tashlashlar

2023-10-02 13:22 UTC, Xolmuratov02 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Domain/Entities/ListingComment.cs
> +        public ListingComment(Guid writtenBy, string comment, Guid listingId)
B6sh joy va qator tashlashlar

2023-10-02 13:31 UTC, Xolmuratov02 approved these changes

2023-10-02 13:31 UTC, Xolmuratov02 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ListingServices/ListingCategoryService.cs
Bir marta qator tashlasa yetadi

2023-10-03 04:28 UTC, rashidovasadbek commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/ReservationServices/ReservationOccupancyService.cs
>                  await _appDataContext.ReservationOccupancies.SaveChangesAsync();
savechange ni ichida cancellationToken qolib ketipti

2023-10-03 04:33 UTC, rashidovasadbek commented on src/Training.AirBnb.Clone.Backend/Test Console/Program.cs
> +//await countryService.CreateAsync(country4);
program dagi tekshirishlar keyinchalik tasir qilmaydimi

2023-10-03 05:05 UTC, rashidovasadbek submitted a review, later dismissed

2023-10-03 08:52 UTC, Xolmuratov02 approved these changes

2023-10-03 08:54 UTC, Xolmuratov02 submitted a review, later dismissed

2023-10-03 12:08 UTC, Ilxom-22 approved these changes

2023-10-03 12:09 UTC, Ilxom-22 approved these changes

2023-10-03 12:10 UTC, rashidovasadbek approved these changes

2023-10-03 12:10 UTC, merged