PhoneNumber Service CRUD and others
sulton-max/Training.AirBnb.Clone pull request #84
Opened 2023-10-02 07:03 UTC by Xolmuratov02

2023-10-02 13:04 UTC, rashidovasadbek commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/PhoneNumberServices/PhoneNumberService.cs
> +            return false;
IsNullWhiteSpace ni o'zi yetarli

2023-10-02 13:12 UTC, rashidovasadbek commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/PhoneNumberServices/PhoneNumberService.cs
> +            return false;
yana CRUD methodlari joylashish o'rnini o'zgartirib  qo'ying shabloni gruhda bor

2023-10-02 13:45 UTC, Abdurahmon0412 requested changes

2023-10-02 13:45 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/PhoneNumberServices/PhoneNumberService.cs
> +        if (updatedNumber is null)
updateni ichida yana qayta tekshirish shart emas 
chunki getbyId da uzi nullga tekshirilgan

2023-10-02 13:45 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/PhoneNumberServices/PhoneNumberService.cs
> +            throw new EntityException<PhoneNumber>("Invalid phone number");
IsvalidPhoneNumber ni ishlashi sal boshqacharoq 
ifni ichida inkor qilgansiz likin u yerdan tugri bo'lsa xato keladi 
qandaydir o'zgartirish kerak

2023-10-02 13:45 UTC, Abdurahmon0412 commented on src/Training.AirBnb.Clone.Backend/Backend Project/Infrastructure/Services/PhoneNumberServices/PhoneNumberService.cs
> +             .Any(number => number.UserPhoneNumber == phoneNumber);
_appdataContext.PhoneNumbersni o'rniga hamma joyda getUndeleted methodlarni ishlatishiz kerak

2023-10-03 09:02 UTC, rashidovasadbek approved these changes

2023-10-03 12:04 UTC, Abdurahmon0412 approved these changes

2023-10-03 12:04 UTC, merged